# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title pcop_backend
#' @name pcop_backend
#' @description Internal backend used by \code{pcop()} to compute the principal curve defined in Delicado (2001) \doi{10.1007/s001800300145}.
#' @param x Numeric matrix of input points; see \code{pcop()}.
#' @param c_d Distance/scaling parameter passed from \code{pcop()}.
#' @param c_h Bandwidth scaling parameter passed from \code{pcop()}.
#' @return Numeric matrix consumed by \code{pcop()}.
#' @keywords internal
pcop_backend <- function(x, c_d, c_h) {
    .Call(`_Rpcop_pcop_backend`, x, c_d, c_h)
}

