# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pcop <- function(x, c_d, c_h, profreq = 1L, nparts = 4L) {
    .Call('_Rpcop_pcop', PACKAGE = 'Rpcop', x, c_d, c_h, profreq, nparts)
}

