#' Principal Curves of Oriented Points
#'
#' Core package documentation generated by roxygen2.
#'
#' @keywords internal
"_PACKAGE"

#' @useDynLib Rpcop, .registration = TRUE
#' @importFrom Rcpp evalCpp
NULL
